// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package orm

var TableNames = struct {
	Friendships  string
	UserAccounts string
}{
	Friendships:  "friendships",
	UserAccounts: "user_accounts",
}
