package repository

import "github.com/friendsofgo/errors"

var (
	FriendshipAlreadyExist       = errors.New("orm: unable to insert into friendships: pq: duplicate key value violates unique constraint \"unique_friends\"")
	UserAlreadyExist             = errors.New("orm: unable to insert into user_accounts: pq: duplicate key value violates unique constraint \"user_accounts_email_key\"")
	InternalErrorAddUser         = errors.New("orm: unable to insert into user_accounts: all expectations were already fulfilled, call to Query 'INSERT INTO \"user_accounts\" (\"name\",\"email\") VALUES ($1,$2) RETURNING \"user_id\"' with args [{Name: Ordinal:1 Value:InternalErrorUser} {Name: Ordinal:2 Value:internal-error-email@example.com}] was not expected")
	InternalErrorCheckEmail      = errors.New("orm: failed to check if user_accounts exists: all expectations were already fulfilled, call to Query 'SELECT COUNT(*) FROM \"user_accounts\" WHERE (\"user_accounts\".\"email\" = $1) LIMIT 1;' with args [{Name: Ordinal:1 Value:internal-error-email@example.com}] was not expected")
	InternalErrorAddFriendship   = errors.New("orm: unable to insert into friendships: all expectations were already fulfilled, call to Query 'INSERT INTO \"friendships\" (\"user_email_1\",\"user_email_2\") VALUES ($1,$2) RETURNING \"friendship_id\"' with args [{Name: Ordinal:1 Value:internal-error-email_1@example.com} {Name: Ordinal:2 Value:internal-error-email_2@example.com}] was not expected")
	InternalErrorGetBlockedList  = errors.New("orm: failed to assign all query results to Subscription slice: bind failed to execute query: all expectations were already fulfilled, call to Query 'SELECT \"subscription\".* FROM \"subscription\" WHERE (\"subscription\".\"requester\" = $1) AND (\"subscription\".\"status\" = $2);' with args [{Name: Ordinal:1 Value:requester2@example.com} {Name: Ordinal:2 Value:blocked}] was not expected")
	InternalErrorCheckFriendship = errors.New("orm: failed to check if friendships exists: all expectations were already fulfilled, call to Query 'SELECT COUNT(*) FROM \"friendships\" WHERE ((user_email_1 = $1 AND user_email_2 = $2) OR (user_email_1 = $3 AND user_email_2 = $4)) LIMIT 1;' with args [{Name: Ordinal:1 Value:internal-error-email_1@example.com} {Name: Ordinal:2 Value:internal-error-email_2@example.com} {Name: Ordinal:3 Value:internal-error-email_2@example.com} {Name: Ordinal:4 Value:internal-error-email_1@example.com}] was not expected")
	InternalErrorGetFollowedList = errors.New("orm: failed to assign all query results to Subscription slice: bind failed to execute query: all expectations were already fulfilled, call to Query 'SELECT \"subscription\".* FROM \"subscription\" WHERE (\"subscription\".\"target\" = $1) AND (\"subscription\".\"status\" = $2);' with args [{Name: Ordinal:1 Value:target2@example.com} {Name: Ordinal:2 Value:followed}] was not expected")
	InternalErrorUpdateTopic     = errors.New("orm: unable to update all for user_accounts: all expectations were already fulfilled, call to ExecQuery 'UPDATE \"user_accounts\" SET \"topic\" = $1, \"topic_body\" = $2 WHERE (\"user_accounts\".\"email\" = $3);' with args [{Name: Ordinal:1 Value:updated} {Name: Ordinal:2 Value:Hello World! mentioned_email@example.com} {Name: Ordinal:3 Value:update_user_email@example.com}] was not expected")
	InternalErrorGetFriendList   = errors.New("orm: failed to assign all query results to Friendship slice: bind failed to execute query: all expectations were already fulfilled, call to Query 'SELECT \"friendships\".* FROM \"friendships\" WHERE (user_email_1 = $1 OR user_email_2 = $2);' with args [{Name: Ordinal:1 Value:already_exist_email_1@example.com} {Name: Ordinal:2 Value:already_exist_email_1@example.com}] was not expected")
)
